# Generated by Django 2.2.7 on 2019-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('cca', models.TextField()),
                ('languages', models.TextField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
